export const ShoutoutTitlesArray = [
  { key: "default", value: "NA" },
  { key: "AdventureBuddy", value: "Adventure Buddy" },
  { key: "AngelEyes", value: "Angel Eyes" },
  { key: "Badmosss", value: "Badmosss" },
  { key: "BestBehan", value: "Best Behan" },
  { key: "BestBhai", value: "Best Bhai" },
  { key: "Bahanebaaz", value: "Bahanebaaz" },
  { key: "Bandar", value: "Bandar" },
  { key: "Bandariyaa", value: "Bandariyaa" },
  { key: "Bhabhiji", value: "Bhabhiji" },
  { key: "ClassClown", value: "Class Clown" },
  { key: "Crush", value: "Crush" },
  { key: "Chatterbox", value: "Chatterbox" },
  { key: "Creative", value: "Creative" },
  { key: "Cutie", value: "Cutie" },
  { key: "Confidant", value: "Confidant" },
  { key: "Dramebaaz", value: "Dramebaaz" },
  { key: "DilChor", value: "Dil Chor" },
  { key: "EkdumBindass", value: "Ekdum Bindass" },
  { key: "FunniestClassmate", value: "Funniest Classmate" },
  { key: "GroupKiShaan", value: "Group Ki Shaan" },
  { key: "GyaaniBaba", value: "Gyaani Baba" },
  { key: "Jugadu", value: "Jugadu" },
  { key: "Kanjoos", value: "Kanjoos" },
  { key: "KingOfMyHeart", value: "King of My Heart" },
  { key: "Khadoos", value: "Khadoos" },
  { key: "LastMinuteTutor", value: "Last Minute Tutor" },
  { key: "MultiTalented", value: "Multi Talented" },
  { key: "MastiKhor", value: "Masti Khor" },
  { key: "MissPerfect", value: "Miss Perfect" },
  { key: "MostCharmingGuy", value: "Most Charming Guy" },
  { key: "MostHelpfulClassmate", value: "Most Helpful Classmate" },
  { key: "MyStrongestPillar", value: "My Strongest Pillar" },
  { key: "NakhreAtPeak", value: "Nakhre at Peak" },
  { key: "PasandidaAurat", value: "Pasandida Aurat" },
  { key: "PasandidaMard", value: "Pasandida Mard" },
  { key: "Pakau", value: "Pakau" },
  { key: "ParamSundarKanya", value: "Param Sundar Kanya" },
  { key: "ProblemSolver", value: "Problem Solver" },
  { key: "Sanskaari", value: "Sanskaari" },
  { key: "SabseSundarMuskan", value: "Sabse Sundar Muskan" },
  { key: "SilentKiller", value: "Silent Killer" },
  { key: "SleepyHead", value: "Sleepy Head" },
  { key: "SmartAF", value: "Smart AF" },
  { key: "SocialButterfly", value: "Social Butterfly" },
  { key: "Soulmate", value: "Soulmate" },
  { key: "Shy", value: "Shy" },
  { key: "ShyBandar", value: "Shy Bandar" },
  { key: "Sweetheart", value: "Sweetheart" },
  { key: "Romeo", value: "Romeo" },
  { key: "Rude", value: "Rude" },
  { key: "TheGossipQueen", value: "The Gossip Queen" },
  { key: "Topper", value: "Topper" },
  { key: "Troublemaker", value: "Troublemaker" },
  { key: "UffVoAankhein", value: "Uff Vo Aankhein" },
];

//
